/** Semantic color tokens — reference via CSS custom properties for theme support. */
export const colors = {
  fg: {
    primary: "var(--color-fg-primary)",
    secondary: "var(--color-fg-secondary)",
    tertiary: "var(--color-fg-tertiary)",
    inverse: "var(--color-fg-inverse)",
    disabled: "var(--color-fg-disabled)",
    placeholder: "var(--color-fg-placeholder)",
    helper: "var(--color-fg-helper)",
    label: "var(--color-fg-label)",
    interactive: "var(--color-fg-interactive)",
    interactiveHover: "var(--color-fg-interactive-hover)",
    interactiveActive: "var(--color-fg-interactive-active)",
    success: "var(--color-fg-success)",
    danger: "var(--color-fg-danger)",
    warning: "var(--color-fg-warning)",
    info: "var(--color-fg-info)",
    onDark: "var(--color-fg-on-dark)",
    onLight: "var(--color-fg-on-light)",
  },
  bg: {
    canvas: "var(--color-bg-canvas)",
    surface: "var(--color-bg-surface)",
    elevated: "var(--color-bg-elevated)",
    sunken: "var(--color-bg-sunken)",
    inverse: "var(--color-bg-inverse)",
    disabled: "var(--color-bg-disabled)",
    backdrop: "var(--color-bg-backdrop)",
    floating: "var(--color-bg-floating)",
    primary: "var(--color-bg-primary)",
    primaryHover: "var(--color-bg-primary-hover)",
    primaryActive: "var(--color-bg-primary-active)",
    primarySubtle: "var(--color-bg-primary-subtle)",
    neutral: "var(--color-bg-neutral)",
    neutralHover: "var(--color-bg-neutral-hover)",
    neutralActive: "var(--color-bg-neutral-active)",
    neutralSubtle: "var(--color-bg-neutral-subtle)",
    neutralMuted: "var(--color-bg-neutral-muted)",
    neutralMutedHover: "var(--color-bg-neutral-muted-hover)",
    success: "var(--color-bg-success)",
    successHover: "var(--color-bg-success-hover)",
    successSubtle: "var(--color-bg-success-subtle)",
    danger: "var(--color-bg-danger)",
    dangerHover: "var(--color-bg-danger-hover)",
    dangerSubtle: "var(--color-bg-danger-subtle)",
    warning: "var(--color-bg-warning)",
    warningHover: "var(--color-bg-warning-hover)",
    warningSubtle: "var(--color-bg-warning-subtle)",
    info: "var(--color-bg-info)",
    infoHover: "var(--color-bg-info-hover)",
    infoSubtle: "var(--color-bg-info-subtle)",
  },
  border: {
    subtle: "var(--color-border-subtle)",
    default: "var(--color-border-default)",
    strong: "var(--color-border-strong)",
    disabled: "var(--color-border-disabled)",
    inverse: "var(--color-border-inverse)",
    primary: "var(--color-border-primary)",
    primarySubtle: "var(--color-border-primary-subtle)",
    neutralSubtle: "var(--color-border-neutral-subtle)",
    success: "var(--color-border-success)",
    successSubtle: "var(--color-border-success-subtle)",
    danger: "var(--color-border-danger)",
    dangerSubtle: "var(--color-border-danger-subtle)",
    warning: "var(--color-border-warning)",
    warningSubtle: "var(--color-border-warning-subtle)",
    info: "var(--color-border-info)",
    infoSubtle: "var(--color-border-info-subtle)",
  },
  ring: {
    primary: "var(--color-ring-primary)",
    neutral: "var(--color-ring-neutral)",
    success: "var(--color-ring-success)",
    danger: "var(--color-ring-danger)",
    warning: "var(--color-ring-warning)",
    info: "var(--color-ring-info)",
  },
} as const;

/** Light theme raw values — for non-CSS contexts (e.g. testing, SSR). */
export const lightTheme = {
  fg: {
    primary: "#0a0a0a",
    secondary: "#696969",
    tertiary: "#aaaaaa",
    inverse: "#ffffff",
    disabled: "#cdcdcd",
    onDark: "#ffffff",
    onLight: "#0a0a0a",
  },
  bg: {
    canvas: "#ffffff",
    surface: "#fafafa",
    elevated: "#f0f0f0",
    inverse: "#000000",
    primary: "#9ad81a",
    primaryHover: "#7fc000",
    neutral: "#0a0a0a",
    success: "#10b981",
    danger: "#ef4444",
    warning: "#f59e0b",
    info: "#0ea5e9",
  },
  border: {
    subtle: "#e1e1e1",
    default: "#cdcdcd",
    strong: "#aaaaaa",
    inverse: "#373737",
  },
  ring: {
    primary: "#9ad81a",
    neutral: "#0a0a0a",
  },
} as const;

/** Dark theme raw values — for non-CSS contexts (e.g. testing, SSR). */
export const darkTheme = {
  fg: {
    primary: "#fafafa",
    secondary: "#aaaaaa",
    tertiary: "#696969",
    inverse: "#0a0a0a",
    disabled: "#505050",
    onDark: "#ffffff",
    onLight: "#0a0a0a",
  },
  bg: {
    canvas: "#000000",
    surface: "#0a0a0a",
    elevated: "#1e1e1e",
    inverse: "#ffffff",
    primary: "#9ad81a",
    primaryHover: "#7fc000",
    neutral: "#ffffff",
    success: "#10b981",
    danger: "#ef4444",
    warning: "#f59e0b",
    info: "#0ea5e9",
  },
  border: {
    subtle: "#373737",
    default: "#505050",
    strong: "#aaaaaa",
    inverse: "#e1e1e1",
  },
  ring: {
    primary: "#9ad81a",
    neutral: "#ffffff",
  },
} as const;

/** Color palette primitives — for reference only, prefer semantic tokens. */
export const palette = {
  primary: {
    50: "#f7faef",
    100: "#f0f8dd",
    200: "#e2f5b8",
    300: "#d1f189",
    400: "#bcec54",
    500: "#9ad81a",
    600: "#7fc000",
    700: "#669a03",
    800: "#4e7206",
    900: "#345006",
    950: "#1f3204",
  },
  neutral: {
    50: "#fafafa",
    100: "#f0f0f0",
    200: "#e1e1e1",
    300: "#cdcdcd",
    400: "#aaaaaa",
    500: "#878787",
    600: "#696969",
    700: "#505050",
    800: "#373737",
    900: "#1e1e1e",
    950: "#0a0a0a",
  },
} as const;
